#cloud-config
users:
  - name: user
    groups: sudo
    shell: /bin/bash
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOlVk5vLOuYAbO0puu4TsKBLxF2EAj37hZor+zIsPHjV nataliya-pischuk@netology
